### ISSUE TITLE
All articles go to global feed

### ISSUE THREAD

**Issue by jameskentTX** [team-alembic/realworld#11]
And I wanted to learn phoenix liveview from that code :(
Big disappointment.

**Comment by zachdaniel** [comment]
I've modified the title to more accurately reflect the issues that you've mentioned. There is realtime in the app, specifically when adding comments. However, I am aware that not everyone will have the time to look more closely than at a surface level, and may not have noticed that.

With that in mind, I've added realtime updates for likes on posts. Perhaps that will enlighten folks in the future.

**Comment by jameskentTX** [comment]
Thank you for changes. But it is still partly a static page. When you add article as one user, another user has to reload page to see change. How ancient it is?
And in my feed I should see all my articles. If I see nothing there, what's the point of that option?

If I may suggest...
Maybe this is a good idea to see database update, worthy of implementation here:
https://www.erlang-solutions.com/blog/let-your-database-update-you-with-ectowatch/

**Comment by zachdaniel** [comment]
Remember that this is a free example application and can only have so much effort applied towards it. No one is paid to make this.

As for your points: liveness on a website is something that must be carefully designed. For instance, if I'm looking at a list sorted by created timestamp descending, new items should not be added as they are created. Imagine if your twitter feed automatically put new tweets at the top every time someone tweeted.

PRs welcome to add a feature similar to twitter, where an element is added that says "new articles have been added, click here to load them".

**Comment by zachdaniel** [comment]
Also, you've misunderstood "my feed". That is for articles from other users that you've followed. To see your own articles you'd go to your own author page.

Remember that we did not design this app. It's an implementation of someone else's demo app.
