### ISSUE TITLE
Adding example for one-to-many which is not the user, like category for an article?

### ISSUE THREAD

**Issue by bandesz** [team-alembic/realworld#12]
In a similar situation, I struggle to make such a relationship work, using the latest Ash version and generators. Unfortunately it doesn't help, that the generators create quite different code from realworld.

The below examples are not related to realworld.

On the Article:
```
actions do
    defaults [:read, :destroy, create: :*, update: :*]
end

relationships do
    belongs_to :category, Example.Category do
      writable? true
      allow_nil? true
    end
end
```

In the form:
```
<.input
  field={@form[:category]}
  type="select"
  label="Category"
  prompt="None"
  options={Enum.map(@categories, &{&1.name, &1.id})}
  value={if @form[:category], do: @form[:category].id, else: ""}
/>
```

The category is never saved for either new or existing articles.

The validation also removes the value of category.

The code uses the generated `AshPhoenix.Form` calls:

```
AshPhoenix.Form.validate(socket.assigns.form, article_params)
[...]
AshPhoenix.Form.submit(socket.assigns.form, params: article_params)
```

I tried multiple approaches, none of them works :(

**Comment by zachdaniel** [comment]
If you are doing a `one_to_many`, you'd be looking for `has_many :categories, Example.Category`. That would likely be the root of the issue.

Then you'd need to use the nested forms using `<.inputs_for`, as laid out in the `AshPhoenix.Form` docs. https://hexdocs.pm/ash_phoenix/AshPhoenix.Form.html#module-working-with-related-data

**Comment by bandesz** [comment]
In my example category would be one_to_many, so an article would have either no category or a single category. Would we still need nested forms for showing a simple select field to set the category_id?

**Comment by zachdaniel** [comment]
Oh, no you wouldn't need that. Sorry, I misread the original issue. You should be editing `form[:category_id]` not `form[:category]`
