### ISSUE TITLE
Please clarify mix.exs Elixir version mismatch with README.md requirement

### ISSUE THREAD

**Issue by someones-github-account** [team-alembic/realworld#6]
README.me

Prerequisites

    erlang 25.2 and elixir 1.14.2-otp-25
    PostgreSQL 14.6

yet, mix.exs

﻿elixir: "~> 1.12",

PS Many thanks for updating this repo to Ash v3 - I'm just starting out with Ash and it's the 'future today'!

**Comment by zachdaniel** [comment]
Fixed :)

**Comment by someones-github-account** [comment]
Thanks @zachdaniel - you're so quick at helping!
